### ISSUE TITLE
Cannot find dataset on zenodo

### ISSUE THREAD

**Issue by Mikalls** [pommes-public/pommesdata#80]
Hello!
        Because I can't get the dataset through the program, I want to download the dataset, but I can't find the dataset on Zenodo. I hope to get your help.
Best regards!

**Comment by jokochems** [comment]
Dear Mikalls,
thank you very much for opening this issue.

The datasets are not yet on Zenodo and I assume this will not happen in the next weeks. There is an (old) open issue on that, but I do not really have the time to address in the near future: https://github.com/pommes-public/pommesdata/issues/21 and also, some fixes are still ongoing.

I integrated an `environment.yml` file, but I must admit that I also do not have the capacity to keep it and the code updated and working with more recent versions of dedicated packages.

This can be installed using - assuming you are using conda as package manager
```
conda env create -f environment.yml
```

Anyways, I've installed the latest version using the dependencies for testing purposes and noticed that there were some things missing (`seaborn`) and other dependencies (the `fiona` import of `geopandas`) were causing trouble.

So my suggested solution is that I simply export and dump the dependencies I'm using. I'll quickly do so and come back to this issue with further instructions on how to make use of it.

**Comment by jokochems** [comment]
Dear @Mikalls,

please find a file `pommesdata_env.yml` at the top level of the repository.

You can install this using
```
conda env create -f pommesdata_env.yml
```

This should allow you the run the code and produce the desired output. If this is not the case, please let me know.
I learned that the thing with geodata libraries is that they can be very picky and behave differently for different operation systems.

If this still does not suit you, I could provide you with already compiled output files.

**Comment by Mikalls** [comment]
Hi, jokochems,

Thanks for your help!! I will try your method.

Best,
Mikalls

**Comment by Mikalls** [comment]
Dear @jokochems ,

I don't think I can get a satisfactory output data. An error occurred after running the file. If you can, I hope you can provide the compiled output file.

Best,
Mikalls

**Comment by jokochems** [comment]
Hi @Mikalls,

I'm sorry, it did not work out for you. I suppose it should be due to you assumably using another operation system for which the geodata packages don't work. The remainder should actually not cause trouble.

Nevermind, for now, I uploaded some compiled data for 2030 / investment modelling here:
https://gigamove.rwth-aachen.de/de/download/88b864b9d2b763a303a7205145dbf498 (valid only for 14 days)

Please drop me an email to
 
![image](https://user-images.githubusercontent.com/40718083/226196360-2e2afd82-47d3-4cae-9099-74cd1f25d375.png)

so I can send you the password.

Also, please let me know if you were looking for something else, like status quo data for 2019 or whatever. I could upload this in the same manner.

Best regards,
Johannes

**Comment by jokochems** [comment]
Dear @Mikalls,

sorry for the inconvenience. In order to put the output files to Zenodo, I guess they lack a little bit of polishing and additional metadata description at first, which I currently cannot offer due to some time restrictions. There is an open pull request, though.

But for now, as stated above, feel free to let me know, what in particular you are interested in.

> Nevermind, for now, I uploaded some compiled data for 2030 / investment modelling here:
> https://gigamove.rwth-aachen.de/de/download/88b864b9d2b763a303a7205145dbf498 (valid only for 14 days)

The file sharing system I used above is hosted by the university of Aachen, Germany by the way and dedicated to large data exchange among (I guess mostly German) academia.

**Comment by jokochems** [comment]
@Mikalls I'll close the issue. Feel free to get in touch with me again when you require the data. I'll try to provide compiled data for Zenodo within the next half year.
